name: build

on: [push, pull_request]

env:
  CI: "1"

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: eris37714/oneapi-dpcpp
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run
        run: |
          cd build
          ./fpga_emu
